# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [1]:
import numpy as np

# Creating the arrays as per the instructions

# 1-D array of zeros
zeros = np.zeros(10)

# 1-D array of vowels
vowels = np.array(['a', 'e', 'i', 'o', 'u'])

# 2-D array of ones with specified shape and dtype
ones = np.ones((2, 5), dtype=int)

# Nested Python lists for myarray1
myarray1_data = [
    [2.7, 0, -2],
    [3.4, 10.6, 0],
    [-19, 99.9, 13]
]
myarray1 = np.array(myarray1_data)

# 2-D array myarray2 using arange
myarray2 = np.arange(4, 4 + 4 * 15, 4).reshape(3, 5).astype(float)

# Displaying the arrays
print("Zeros Array:")
print(zeros)
print("\nVowels Array:")
print(vowels)
print("\nOnes Array:")
print(ones)
print("\nMyarray1:")
print(myarray1)
print("\nMyarray2:")
print(myarray2)




Zeros Array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Vowels Array:
['a' 'e' 'i' 'o' 'u']

Ones Array:
[[1 1 1 1 1]
 [1 1 1 1 1]]

Myarray1:
[[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

Myarray2:
[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [3]:
import numpy as np

# Creating the arrays
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2, 5), dtype=int)

myarray1_data = [
    [2.7, 0, -2],
    [3.4, 10.6, 0],
    [-19, 99.9, 13]
]
myarray1 = np.array(myarray1_data)

myarray2 = np.arange(4, 4 + 4 * 15, 4).reshape(3, 5).astype(float)

# Finding dimensions, shape, size, data type, and itemsize for each array
zeros_info = {
    "dimensions": zeros.ndim,
    "shape": zeros.shape,
    "size": zeros.size,
    "dtype": zeros.dtype,
    "itemsize": zeros.itemsize
}

vowels_info = {
    "dimensions": vowels.ndim,
    "shape": vowels.shape,
    "size": vowels.size,
    "dtype": vowels.dtype,
    "itemsize": vowels.itemsize
}

ones_info = {
    "dimensions": ones.ndim,
    "shape": ones.shape,
    "size": ones.size,
    "dtype": ones.dtype,
    "itemsize": ones.itemsize
}

myarray1_info = {
    "dimensions": myarray1.ndim,
    "shape": myarray1.shape,
    "size": myarray1.size,
    "dtype": myarray1.dtype,
    "itemsize": myarray1.itemsize
}

myarray2_info = {
    "dimensions": myarray2.ndim,
    "shape": myarray2.shape,
    "size": myarray2.size,
    "dtype": myarray2.dtype,
    "itemsize": myarray2.itemsize
}

# Reshaping the ones array to have all elements in a single row
ones_reshaped = ones.reshape(1, -1)

# Displaying the 2nd and 3rd element of the array vowels
vowels_elements = vowels[1:3]

# Displaying all elements in the 2nd and 3rd row of the array myarray1
myarray1_rows = myarray1[1:3, :]

# Displaying the elements in the 1st and 2nd column of the array myarray1
myarray1_columns = myarray1[:, 0:2]

# Displaying the elements in the 1st column of the 2nd and 3rd row of the array myarray1
myarray1_specific = myarray1[1:3, 0]

# Reversing the array of vowels
vowels_reversed = vowels[::-1]

# Gathering all the results
results = {
    "zeros_info": zeros_info,
    "vowels_info": vowels_info,
    "ones_info": ones_info,
    "myarray1_info": myarray1_info,
    "myarray2_info": myarray2_info,
    "ones_reshaped": ones_reshaped,
    "vowels_elements": vowels_elements,
    "myarray1_rows": myarray1_rows,
    "myarray1_columns": myarray1_columns,
    "myarray1_specific": myarray1_specific,
    "vowels_reversed": vowels_reversed
}

# Printing results
for key, value in results.items():
    print(f"{key}: {value}\n")


zeros_info: {'dimensions': 1, 'shape': (10,), 'size': 10, 'dtype': dtype('float64'), 'itemsize': 8}

vowels_info: {'dimensions': 1, 'shape': (5,), 'size': 5, 'dtype': dtype('<U1'), 'itemsize': 4}

ones_info: {'dimensions': 2, 'shape': (2, 5), 'size': 10, 'dtype': dtype('int32'), 'itemsize': 4}

myarray1_info: {'dimensions': 2, 'shape': (3, 3), 'size': 9, 'dtype': dtype('float64'), 'itemsize': 8}

myarray2_info: {'dimensions': 2, 'shape': (3, 5), 'size': 15, 'dtype': dtype('float64'), 'itemsize': 8}

ones_reshaped: [[1 1 1 1 1 1 1 1 1 1]]

vowels_elements: ['e' 'i']

myarray1_rows: [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]

myarray1_columns: [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]

myarray1_specific: [  3.4 -19. ]

vowels_reversed: ['u' 'o' 'i' 'e' 'a']



Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [5]:
import numpy as np

# Creating the arrays again to ensure we have the right context
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2, 5), dtype=int)

myarray1_data = [
    [2.7, 0, -2],
    [3.4, 10.6, 0],
    [-19, 99.9, 13]
]
myarray1 = np.array(myarray1_data)

myarray2 = np.arange(4, 4 + 4 * 15, 4).reshape(3, 5).astype(float)

# Operations
# 1. Divide all elements of array ones by 3
ones_divided = ones / 3

# 2. Add the arrays myarray1 and myarray2
# Note: We cannot directly add them due to shape differences.
# We will take only compatible parts or reshape if needed.
myarray_sum = myarray1 + myarray2[:3, :3]  # using only the first 3 columns of myarray2

# 3. Subtract myarray1 from myarray2 (again, taking only compatible parts)
myarray_difference = myarray2[:3, :3] - myarray1

# 4. Multiply myarray1 and myarray2 elementwise
# This will also use the compatible parts
myarray_product = myarray1 * myarray2[:3, :3]

# 5. Matrix multiplication of myarray1 and myarray2
myarray3 = np.matmul(myarray1, myarray2[:3, :3].T)  # Transposing for correct shape

# 6. Divide myarray1 by myarray2
myarray_division = myarray1 / myarray2[:3, :3]

# 7. Find the cube of all elements of myarray1 and divide by 2
myarray1_cubed_divided = (myarray1 ** 3) / 2

# 8. Find the square root of all elements of myarray2 and divide by 2, rounded to 2 decimals
myarray2_sqrt_divided = np.sqrt(myarray2) / 2
myarray2_sqrt_divided_rounded = np.round(myarray2_sqrt_divided, 2)

# Gathering all the results
math_operations_results = {
    "ones_divided": ones_divided,
    "myarray_sum": myarray_sum,
    "myarray_difference": myarray_difference,
    "myarray_product": myarray_product,
    "myarray3": myarray3,
    "myarray_division": myarray_division,
    "myarray1_cubed_divided": myarray1_cubed_divided,
    "myarray2_sqrt_divided_rounded": myarray2_sqrt_divided_rounded
}

# Printing results
for key, value in math_operations_results.items():
    print(f"{key}:\n{value}\n")





ones_divided:
[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]

myarray_sum:
[[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]

myarray_difference:
[[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]

myarray_product:
[[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]

myarray3:
[[-1.3200e+01  8.0000e-01  1.4800e+01]
 [ 9.8400e+01  3.7840e+02  6.5840e+02]
 [ 8.7920e+02  2.7572e+03  4.6352e+03]]

myarray_division:
[[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]

myarray1_cubed_divided:
[[ 9.841500e+00  0.000000e+00 -4.000000e+00]
 [ 1.965200e+01  5.955080e+02  0.000000e+00]
 [-3.429500e+03  4.985015e+05  1.098500e+03]]

myarray2_sqrt_divided_rounded:
[[1.   1.41 1.73 2.   2.24]
 [2.45 2.65 2.83 3.   3.16]
 [3.32 3.46 3.61 3.74 3.87]]



Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [7]:
import numpy as np

# Creating the arrays again to ensure we have the right context
ones = np.ones((2, 5), dtype=int)
myarray2 = np.arange(4, 4 + 4 * 15, 4).reshape(3, 5).astype(float)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
myarray1_data = [
    [2.7, 0, -2],
    [3.4, 10.6, 0],
    [-19, 99.9, 13]
]
myarray1 = np.array(myarray1_data)

# Finding the transpose of ones and myarray2
ones_transpose = ones.T
myarray2_transpose = myarray2.T

# Sorting the array vowels in reverse
vowels_sorted_reverse = np.sort(vowels)[::-1]

# Sorting the array myarray1 such that it brings the lowest value of the column in the first row and so on
myarray1_sorted = np.sort(myarray1, axis=0)  # Sort along columns

# Gathering results
transpose_results = {
    "ones_transpose": ones_transpose,
    "myarray2_transpose": myarray2_transpose,
    "vowels_sorted_reverse": vowels_sorted_reverse,
    "myarray1_sorted": myarray1_sorted
}

# Printing results
for key, value in transpose_results.items():
    print(f"{key}:\n{value}\n")




ones_transpose:
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]

myarray2_transpose:
[[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]

vowels_sorted_reverse:
['u' 'o' 'i' 'e' 'a']

myarray1_sorted:
[[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]



Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [13]:
import numpy as np

# Creating a 2-D array called myarray4 using arange
myarray4 = np.arange(-1, -1 + 42 * 0.25, 0.25).reshape(14, 3)

# Splitting the array row-wise into 3 equal parts
myarray4_split = np.array_split(myarray4, 3)

# Printing the result of the split
for i, part in enumerate(myarray4_split):
    print(f"Part {i + 1}:\n{part}\n")



Part 1:
[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]

Part 2:
[[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]

Part 3:
[[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]



Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [11]:
import numpy as np

# Creating a 2-D array called myarray4 using arange
myarray4 = np.arange(-1, -1 + 42 * 0.25, 0.25).reshape(14, 3)

# Finding the sum of all elements
total_sum = np.sum(myarray4)

# Finding the sum of all elements row-wise
row_sum = np.sum(myarray4, axis=1)

# Finding the sum of all elements column-wise
column_sum = np.sum(myarray4, axis=0)

# Finding the max of all elements
max_value = np.max(myarray4)

# Finding the min of all elements in each row
min_value_row = np.min(myarray4, axis=1)

# Finding the mean of all elements in each row
mean_value_row = np.mean(myarray4, axis=1)

# Finding the standard deviation column-wise
std_dev_column = np.std(myarray4, axis=0)

# Gathering results
statistics_results = {
    "total_sum": total_sum,
    "row_sum": row_sum,
    "column_sum": column_sum,
    "max_value": max_value,
    "min_value_row": min_value_row,
    "mean_value_row": mean_value_row,
    "std_dev_column": std_dev_column
}

# Printing results
for key, value in statistics_results.items():
    print(f"{key}:\n{value}\n")





total_sum:
173.25

row_sum:
[-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]

column_sum:
[54.25 57.75 61.25]

max_value:
9.25

min_value_row:
[-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]

mean_value_row:
[-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]

std_dev_column:
[3.02334666 3.02334666 3.02334666]



#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [21]:
import pandas as pd
import numpy as np

# Assuming data has been provided as a dictionary
data = {
    'Country': ['Afghanistan', 'Albania', 'Saudi Arabia', 'Algeria', 'Argentina', 'Australia', 'Austria', 'Bahrain', 'Bangladesh'],
    'Capital City': ['Kabul', 'Tirana', 'Riyadh', 'Algiers', 'Buenos Aires', 'Canberra', 'Vienna', 'Manama', 'Dhaka'],
    'Latitude': [34.5289, 41.3275, 24.6905, 36.7525, -34.6051, -35.2835, 48.2064, 26.2154, 23.7104],
    'Longitude': [69.1725, 19.8189, 46.7096, 3.042, -58.4004, 149.1281, 16.3707, 50.5832, 90.4074]
}

# Convert the data to a DataFrame
df = pd.DataFrame(data)

# Get coordinates of Riyadh
riyadh_lat, riyadh_lon = df[df['Capital City'] == 'Riyadh'][['Latitude', 'Longitude']].values[0]

# Convert latitude and longitude columns to NumPy arrays
latitudes = df['Latitude'].to_numpy()
longitudes = df['Longitude'].to_numpy()

# Compute the Euclidean distance from Riyadh to all other capitals
distances = np.sqrt((latitudes - riyadh_lat)**2 + (longitudes - riyadh_lon)**2)

# Set distance of Riyadh to itself as infinity to exclude it
distances[df['Capital City'] == 'Riyadh'] = np.inf

# Find the index of the minimum distance
min_distance_idx = np.argmin(distances)

# Get the closest capital city information
closest_city = df.iloc[min_distance_idx]

# Output the result
print("Closest capital city to Riyadh:")
print(f"City: {closest_city['Capital City']}")
print(f"Latitude: {closest_city['Latitude']}")
print(f"Longitude: {closest_city['Longitude']}")







Closest capital city to Riyadh:
City: Manama
Latitude: 26.2154
Longitude: 50.5832


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

FileNotFoundError: [Errno 2] No such file or directory: 'country-capital-lat-long-population.csv'